"""
Email alert system - sends instant notifications when 🔥 HOT deals are found.
Requires SMTP_EMAIL and SMTP_PASSWORD in your .env file.
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv()

SMTP_EMAIL = os.getenv("SMTP_EMAIL", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
ALERT_RECIPIENTS = [os.getenv("ALERT_RECIPIENTS", SMTP_EMAIL)]

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


def send_hot_lead_alert(hot_leads):
    """Sends an email digest of hot leads."""
    
    if not SMTP_EMAIL or not SMTP_PASSWORD:
        print("   [INFO] SMTP Email not configured in .env. Skipping alerts.")
        return
    
    if not hot_leads:
        return
        
    print(f"   [ALERTS] Sending {len(hot_leads)} hot lead alerts via Email to {ALERT_RECIPIENTS[0]}...")
    
    # Build email body
    body_lines = [
        "<h2>🔥 HOT Deal Flow Leads Detected</h2>",
        f"<p>Your AI engine found <strong>{len(hot_leads)}</strong> high-scoring leads:</p>",
        "<table border='1' cellpadding='8' cellspacing='0' style='border-collapse:collapse;font-family:sans-serif;'>",
        "<tr style='background:#f4f4f4;'><th>Score</th><th>Niche</th><th>Headline</th><th>Source</th></tr>"
    ]
    
    for lead in hot_leads:
        score = lead.get("lead_score", 0)
        headline = lead.get("headline", "N/A")
        source = lead.get("source", "N/A")
        summary = lead.get("ai_summary", "")
        url = lead.get("url", "#")
        niche = lead.get("industry", "Emerging Tech")
        
        body_lines.append(
            f"<tr>"
            f"<td style='text-align:center;color:red;'><strong>{score}/10</strong></td>"
            f"<td><strong>{niche}</strong></td>"
            f"<td><a href='{url}'>{headline[:80]}</a><br><small>{summary}</small></td>"
            f"<td>{source}</td>"
            f"</tr>"
        )
    
    body_lines.append("</table>")
    body_lines.append("<br><p><em>Generated by your Autonomous Deal Flow Engine (Email Alerts)</em></p>")
    
    html_body = "\n".join(body_lines)
    
    # Create email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🔥 {len(hot_leads)} Hot Leads Found | Deal Flow Engine"
    msg["From"] = SMTP_EMAIL
    msg["To"] = ", ".join(ALERT_RECIPIENTS)
    
    msg.attach(MIMEText(html_body, "html"))
    
    # Send
    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_EMAIL, SMTP_PASSWORD)
            server.sendmail(SMTP_EMAIL, ALERT_RECIPIENTS, msg.as_string())
        print(f"   [ALERTS] Alert sent successfully!")
    except Exception as e:
        print(f"   [FAIL] Email alert failed: {e}")
